// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SearchSongInIndexInvert(arg1) {
  return window['go']['main']['App']['SearchSongInIndexInvert'](arg1);
}

export function SearchSongInTrie(arg1) {
  return window['go']['main']['App']['SearchSongInTrie'](arg1);
}
