// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function SearchSongInIndexInvert(arg1:string):Promise<types.Result>;

export function SearchSongInTrie(arg1:string):Promise<types.Result>;
